# Generated by Django 5.1.1 on 2024-11-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='3354c0c9a97211ef990fc8e265d077b1', max_length=300),
        ),
    ]
